config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
  # config/routes.rb
  root 'welcome#index'
  get "/edit/:id", to: "welcome#show"
  resources :welcome
 #delete get 'welcome/:id', to: 'welcome#destroy'
  post '/users', to: 'welcome#create'
  get '/success', to: 'welcome#index'
 post '/edit', to: 'welcome#update'
 post '/show', to: 'welcome#show'
 #get '/destroy', to: 'welcome#destroy'
 #get 'destroy/:id', to: 'welcome#destroy'
 get 'welcome/:id', to: 'welcome#show'
 get 'welcome/:id/edit', to: 'welcome#show'
 get 'welcome/:id/destroy', to: 'welcome#destroy', as: 'delete_welcome'
# config/routes.rb
#post '/edit/:id/edit', to: 'welcome#update' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/test.rb
class Test < ApplicationRecord
    validates :name, presence: true
    validates :lastname, presence: true
    validates :message, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
   # render plain: "hello world!"
   #__________________________________________________________________READ__
   @info = Test.all #for retrieving data from database
  end
  def show    #for retrieving data from database according to id
    @info = Test.find(params[:id])
  end
  #for create/inserting data _______________________________________
  def new
    @test = Test.new
  end
  
  def create
    #for id to be 1,2,3,4,5,.....in order
    last_id = Test.maximum(:id)
    new_id = last_id.nil? ? 1 : last_id + 1
    @test = Test.new(test_params)
    @test.id = new_id
    if @test.save
      redirect_to '/success'
    else
      render :new, status: :unprocessable_entity
    end
  end
  #_____________________________for update or edit_______________________
  def edit
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])

    if @test.update(test_params)
      redirect_to root_path, notice: 'Record updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  #__________________________________________for deleting record_____________
  def destroy
    @test = Test.find(params[:id])
    @test.destroy
    redirect_to root_path, notice: 'Test was successfully destroyed.'
  end
  private
    def test_params
      params.permit(:name, :lastname, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfirstapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<%= csrf_meta_tags %>
</head>
<!--________________________displaying data in list_____________________
<h1>Users</h1>
<ul>
  <% @info.each do |info| %>
    <li>
      <%= info.name %>
    </li>
    <li>
    <%= info.lastname %>
  </li>
  <li>
  <%= info.message %>
</li>
  <% end %>
</ul>-->
<!-- ___________________________________in__table____________________-->
<h1>Users</h1>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Message</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @info.each do |info| %>
      <tr>
        <!--<td><%= info.id %></td>-->
        <td><%= info.name %></td>
        <td><%= info.lastname %></td>
        <td><%= info.message %></td>
        <td>
        <%= link_to 'Edit 🖋', welcome_path(info)%>
         </td>
         <td>
        <%= link_to '  Delete 🗑', delete_welcome_path(info), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
      </tr>
    <% end %>

  </tbody>
</table>
<hr>
<!--__________________________________________inserting data___________________-->
<h1>Add new user</h1>
<%= form_tag '/users' do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>


  <div class="form-group">
    <label for="user_name">Name</label>
    <%= text_field_tag 'name', nil, class: 'form-control', id: 'user_name' %>
  </div>

  <div class="form-group">
    <label for="user_lastname">Lastname</label>
    <%= text_field_tag 'lastname', nil, class: 'form-control', id: 'user_lastname' %>
  </div>

  <div class="form-group">
    <label for="user_message">Message</label>
    <%= text_area_tag 'message', nil, class: 'form-control', id: 'user_message' %>
  </div>

  <div>
    <%= submit_tag 'Save', class: 'btn btn-primary', data: { disable_with: 'Saving...' } %>
  </div>
<% end %>

app/views/welcome/show.html.erb
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<!--<h1>Users</h1>
<p><%= @info.name %></p>
<p><%= @info.lastname %></p>
<p><%= @info.message %></p>  -->
<br>
<h1>Edit user</h1>
<%= form_tag '/edit' do %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
 <%= hidden_field_tag 'id', @info.id %>
  <div class="form-group">
    <label for="user_name">Name</label>
    <%= text_field_tag 'name',  @info.name, class: 'form-control', id: 'user_name' %>
  </div>

  <div class="form-group">
    <label for="user_lastname">Lastname</label>
    <%= text_field_tag 'lastname',  @info.lastname, class: 'form-control', id: 'user_lastname' %>
  </div>

  <div class="form-group">
    <label for="user_message">Message</label>
    <%= text_area_tag 'message',  @info.message, class: 'form-control', id: 'user_message' %>
  </div>

  <div>
    <%= submit_tag 'update', class: 'btn btn-primary', data: { disable_with: 'Saving...' } %>
  </div>
<% end %>